"""Ingestion: extraction of shapes/styles/geometry from .pptx (Phase 1A)."""

from deckforge_core.ingest.cache import IngestCache, deck_hash  # noqa: F401
from deckforge_core.ingest.parser import (  # noqa: F401
    IngestError,
    IngestResult,
    extract_deck,
    extract_directory,
)
from deckforge_core.ingest.thumbnails import render_thumbnails  # noqa: F401
from deckforge_core.schemas.extracted import (  # noqa: F401
    EMU_PER_INCH,
    EMU_PER_PT,
    ExtractedChart,
    ExtractedChartSeries,
    ExtractedConnector,
    ExtractedDeck,
    ExtractedDeckRecord,
    ExtractedImageRef,
    ExtractedParagraph,
    ExtractedShape,
    ExtractedSlide,
    ExtractedTable,
    ExtractedTextRun,
    SlideGeometry,
    aspect_ratio,
    image_area_fraction,
    shape_text,
    slide_text,
    text_area_fraction,
    text_density,
    total_words,
    total_words_in_deck,
)

__all__ = [
    "IngestError",
    "IngestResult",
    "IngestCache",
    "deck_hash",
    "extract_deck",
    "extract_directory",
    "render_thumbnails",
    "ExtractedTextRun",
    "ExtractedParagraph",
    "ExtractedImageRef",
    "ExtractedChart",
    "ExtractedChartSeries",
    "ExtractedTable",
    "ExtractedConnector",
    "ExtractedShape",
    "ExtractedSlide",
    "ExtractedDeck",
    "ExtractedDeckRecord",
    "SlideGeometry",
    "EMU_PER_INCH",
    "EMU_PER_PT",
    "aspect_ratio",
    "shape_text",
    "slide_text",
    "total_words",
    "total_words_in_deck",
    "text_area_fraction",
    "image_area_fraction",
    "text_density",
]
